const { Client, LocalAuth, MessageMedia } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const fs = require('fs');
const path = require('path');

console.log('Initializing WhatsApp Client...');

const SESSION_DIR = path.join(__dirname, '../.wwebjs_auth/session');

// Gracefully handle browser lock cleanup before starting so we don't wipe out the login session
if (fs.existsSync(SESSION_DIR)) {
    const lockFiles = ['lockfile', 'SingletonLock', 'SingletonCookie', 'SingletonSocket'];
    lockFiles.forEach(file => {
        const filePath = path.join(SESSION_DIR, file);
        if (fs.existsSync(filePath)) {
            try {
                fs.unlinkSync(filePath);
                console.log(`Cleared previous WhatsApp session lock: ${file}`);
            } catch (err) {
                console.error(`Warning: Could not clear ${file}:`, err.message);
            }
        }
    });
}

const client = new Client({
    authStrategy: new LocalAuth(),
    puppeteer: {
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    }
});

let isClientReady = false;
let currentQR = null;

client.on('qr', (qr) => {
    currentQR = qr;
    isClientReady = false;
    console.log('\n======================================================');
    console.log('SCAN THIS QR CODE IN WHATSAPP TO LINK THE BILLING SERVER');
    console.log('======================================================\n');
    qrcode.generate(qr, { small: true });
});

client.on('ready', () => {
    isClientReady = true;
    currentQR = null;
    console.log('\n======================================================');
    console.log('WHATSAPP CLIENT READY! SERVER CAN NOW SEND INVOICE PDFS');
    console.log('======================================================\n');
});

client.on('disconnected', (reason) => {
    isClientReady = false;
    currentQR = null;
    console.log('WhatsApp Client was disconnected:', reason);
    // Auto re-initialize on disconnect to get a new QR
    client.initialize().catch(err => console.error(err));
});

// Initialize the client asynchronously
client.initialize().catch(err => {
    console.error('Failed to initialize WhatsApp Client:', err);
});

/**
 * Sends a PDF invoice to a given phone number.
 * 
 * @param {string} phone - The 10 digit Indian mobile number (or with 91 prefix)
 * @param {string} text - The message body to send alongside the PDF
 * @param {Buffer} pdfBuffer - The raw PDF data buffer generated by puppeteer
 * @param {string} filename - The name of the PDF file to display in WhatsApp
 */
const sendInvoiceToWhatsApp = async (phone, text, pdfBuffer, filename) => {
    if (!isClientReady) {
        console.error('Attempted to send WhatsApp message but client is not ready.');
        throw new Error('WhatsApp Client is not ready. Please scan the QR code on the server terminal.');
    }

    try {
        // Clean phone number. Ensure it has country code '91' and suffix '@c.us'
        let cleanPhone = phone.replace(/\D/g, '');
        if (cleanPhone.length === 10) {
            cleanPhone = '91' + cleanPhone;
        }
        const chatId = `${cleanPhone}@c.us`;

        // Create MessageMedia object from PDF Buffer
        // Safeguard conversion: Puppeteer may return Uint8Array. Buffer.from ensures correct toString conversion.
        const base64Data = Buffer.from(pdfBuffer).toString('base64');
        const media = new MessageMedia('application/pdf', base64Data, filename);

        // Send the message with the attachment
        console.log(`Sending WhatsApp Invoice PDF to ${cleanPhone}...`);
        await client.sendMessage(chatId, text, { media });
        console.log(`Invoice PDF successfully sent to ${cleanPhone}!`);

        return { success: true };
    } catch (error) {
        console.error('Failed to send WhatsApp message:', error);
        throw error;
    }
};

module.exports = {
    client,
    sendInvoiceToWhatsApp,
    isClientReady: () => isClientReady,
    getCurrentQR: () => currentQR
};
